# Generated by Django 5.2.1 on 2025-06-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tiempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_entrada', models.IntegerField(verbose_name='hora de entrada')),
                ('hora_tarifa', models.IntegerField(verbose_name='tarifa de timepo')),
                ('tarifa_id', models.IntegerField(verbose_name='tarifa')),
            ],
        ),
    ]
