# Generated by Django 5.2.3 on 2025-06-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiempo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiempo',
            name='hora_entrada',
        ),
        migrations.RemoveField(
            model_name='tiempo',
            name='hora_tarifa',
        ),
        migrations.RemoveField(
            model_name='tiempo',
            name='tarifa_id',
        ),
        migrations.AddField(
            model_name='tiempo',
            name='contador',
            field=models.IntegerField(blank=True, null=True, verbose_name='contador'),
        ),
        migrations.AddField(
            model_name='tiempo',
            name='horas',
            field=models.IntegerField(blank=True, null=True, verbose_name='horas'),
        ),
        migrations.AddField(
            model_name='tiempo',
            name='minutos',
            field=models.IntegerField(blank=True, null=True, verbose_name='minutos'),
        ),
    ]
