# Generated by Django 5.2.1 on 2025-06-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.TextField(verbose_name='Placa')),
                ('usuario_id', models.IntegerField(verbose_name='usuario')),
                ('fecha_hora', models.IntegerField(verbose_name='fecha')),
            ],
        ),
    ]
