# Generated by Django 5.2.3 on 2025-06-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='fecha_hora',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='usuario_id',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='categoria',
            field=models.TextField(blank=True, verbose_name='categoria'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='documentacion',
            field=models.TextField(blank=True, verbose_name='documentacion'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='modelo',
            field=models.TextField(blank=True, verbose_name='modelo'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo',
            field=models.TextField(blank=True, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.TextField(blank=True, verbose_name='Placa'),
        ),
    ]
