# Generated by Django 5.2.3 on 2025-07-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Placa', models.TextField(verbose_name='Placa')),
                ('matricula_vehiculo', models.TextField(verbose_name='Matricula y vehiculo')),
                ('usuario_id', models.IntegerField(verbose_name='Usuario')),
                ('fecha_ingreso', models.TextField(verbose_name='Fecha de ingreso')),
                ('Servicio_id', models.IntegerField(verbose_name='Servicio')),
            ],
        ),
    ]
