# Generated by Django 5.2.1 on 2025-06-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(verbose_name='nombre')),
                ('apellido', models.TextField(verbose_name='apellido')),
                ('correo', models.TextField(verbose_name='correo')),
                ('rol_id', models.IntegerField(verbose_name='rol')),
            ],
        ),
    ]
