# Generated by Django 5.2.3 on 2025-06-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.TextField(blank=True, verbose_name='apellido'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.TextField(blank=True, verbose_name='correo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.TextField(blank=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol_id',
            field=models.IntegerField(null=True, verbose_name='rol'),
        ),
    ]
