# Generated by Django 5.2.1 on 2025-06-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medios_de_pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medios_de_pago', models.TextField(verbose_name='Medios_de_pago')),
                ('tiempo_parqueo_id', models.IntegerField(verbose_name='Tiempo de parqueo')),
            ],
        ),
    ]
