# Generated by Django 5.2.1 on 2025-06-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agregar', models.TextField(verbose_name='Agregar')),
                ('eliminar', models.TextField(verbose_name='Eliminar')),
                ('editar', models.TextField(verbose_name='Editar')),
                ('consultar', models.TextField(verbose_name='Consultar')),
                ('usuario_id', models.TextField(verbose_name='Usuarios_id')),
                ('rol_id', models.IntegerField(verbose_name='Rol_id')),
            ],
        ),
    ]
